#ifndef ENUMS_H
#define ENUMS_H
#define DECLARE_ENUM(x) namespace x{ enum x{
#define DECLARE_ENUM_CLOSE };}

DECLARE_ENUM(ENCODING)
	AUTO=0,
	ISO_8859_1,
	UTF8,
	SJIS
DECLARE_ENUM_CLOSE;

DECLARE_ENUM(ENCRYPTION)
	NONE=0,
	XOR84,
	VARIABLE_XOR,
	TRANSFORM_THEN_XOR84,
	NT3_KEY
DECLARE_ENUM_CLOSE;

DECLARE_ENUM(StackFrameType)
	UNDEFINED=0,
	SUBROUTINE_CALL,
	FOR_NEST,
	TEXTGOSUB_CALL,
	USERCMD_CALL,
	CSEL_CALL
DECLARE_ENUM_CLOSE;
#endif
